### ISSUE TITLE
Migration from seek-module-toolkit

### ISSUE THREAD

**Issue by 72636c** [seek-oss/skuba#13]
Requirements:

- [x] `skuba build` command that supports CommonJS + ES2015 module outputs (#15)

- [x] `skuba configure` tweaks to accommodate packages

  - [x] Retain `package.json` name, readme, version (#18)

  - [x] Rewrite `package.name` files, main, module, typings (#66)

  - [x] Exclude `skuba-dive` (#66)

  - [x] Exclude `tsconfig.json` baseUrl and paths (#66)

  - [x] Do not modify `package.name` license, private (#66)

- [x] `skuba init` template (#40)

  - [x] Exclude `tsconfig.json` baseUrl and paths (#75)

- [x] `skuba lint` TSDoc support (#75)

- [x] `skuba release` command (e.g. ~~Changesets~~, Semantic Release) (#40)

- [x] [Migration guide](https://github.com/seek-oss/skuba/blob/master/docs/migrating-from-seek-module-toolkit.md) (#56)

**Comment by 72636c** [comment]
Slated for v3.7.0. PRs will be raised to `seek-module-toolkit` to force some alignment prior to migration.
