### ISSUE TITLE
Broadly support user-defined module aliases

### ISSUE THREAD

**Issue by 72636c** [seek-oss/skuba#696]
- [ ] build: #681 via `esbuild`
- [ ] lint: read `tsconfig.json` to dynamically render ESLint import order [pathGroups](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#pathgroups-array-of-objects)?
- [x] node, start: #678 via `tsconfig-paths`
- [x] test: #698 via [moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring)
- [ ] https://github.com/seek-oss/skuba/blob/652ced409f91b579a75284558fcd1e041f7bdf8a/jest/moduleNameMapper.js#L11-L16

**Comment by samchungy** [comment]
We're adopting subpath imports instead of this as part of https://seek-oss.github.io/skuba/docs/deep-dives/esm.html
